version: '3.6'
services:
  postfix_test_587:
    hostname: "postfix"
    image: "boky/postfix"
    restart: always
    healthcheck:
      test: [ "CMD", "sh", "-c", "netstat -an | fgrep 587 | fgrep -q LISTEN" ]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 2
    ports:
      - "1587:587"
    volumes:
      - "./test-keys:/etc/opendkim/keys"
    environment:
      ALLOWED_SENDER_DOMAINS: "example.org"
      INBOUND_DEBUGGING: 1