version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./localdrive/appdata:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - matchmde-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./localdrive/appdata:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - matchmde-network

  #postgres Service
  postgres:
    image: postgres:11.5
    container_name: db
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - ./localdrive/dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: wordpass
      POSTGRES_HOST_AUTH_METHOD: "trust"
      SERVICE_TAGS: dev
      SERVICE_NAME: postgres      
    networks:
      - matchmde-network

#Docker Networks
networks:
  matchmde-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
